// Liste des 50 chansons du blind test.
// - file          : chemin vers le fichier audio (à placer dans le dossier audio/)
// - introEnd      : durée en secondes de l'intro complète (niveau NOOB)
// - chorusStart   : seconde à laquelle démarre le refrain (lecture auto après la réponse)
// - revealDuration: durée en secondes du refrain joué lors de la révélation
const SONGS = [
  { id: 1, title: 'Bad', artist: 'Michael Jackson', file: 'audio/BAD.mp3', introEnd: 17, chorusStart: 130, revealDuration: 8 }, // exemple repris de ta maquette
  { id: 2, title: 'Banquet', artist: 'Bloc Party', file: 'audio/BANQUET.mp3', introEnd: 18, chorusStart: 58, revealDuration: 8 },
  { id: 3, title: 'Kids', artist: 'MGMT', file: 'audio/KIDS.mp3', introEnd: 50, chorusStart: 148, revealDuration: 8 },
  { id: 4, title: 'Kiss', artist: 'Prince', file: 'audio/KISS.mp3', introEnd: 10, chorusStart: 57, revealDuration: 8 },
  { id: 5, title: 'Song 2', artist: 'Blur', file: 'audio/SONG2.mp3', introEnd: 29, chorusStart: 45, revealDuration: 8 },
  { id: 6, title: 'Bohemian like you', artist: 'The Dandy Warhols', file: 'audio/BOHEMIAN.mp3', introEnd: 37, chorusStart: 125, revealDuration: 8 },
  { id: 7, title: 'Can’t Hold Us', artist: 'Macklemore & Ryan Lewis', file: 'audio/HOLD_US.mp3', introEnd: 18, chorusStart: 151, revealDuration: 8 },
  { id: 8, title: 'Can’t Stop', artist: 'Red Hot Chili Peppers', file: 'audio/CANT_STOP.mp3', introEnd: 32, chorusStart: 114, revealDuration: 8 },
  { id: 9, title: 'I Was Made For Lovin You', artist: 'KISS', file: 'audio/MADE_FOR_LOVIN_YOU.mp3', introEnd: 33, chorusStart: 108, revealDuration: 8 },
  { id: 10, title: 'Thunderstruck', artist: 'AC/DC', file: 'audio/THUNDERSTRUCK.mp3', introEnd: 102, chorusStart: 243, revealDuration: 8 },
  { id: 11, title: 'Feel Good', artist: 'Gorillaz', file: 'audio/FEEL_GOOD.mp3', introEnd: 34, chorusStart: 160, revealDuration: 8 },
  { id: 12, title: 'Superstition', artist: 'Stevie Wonder', file: 'audio/SUPERSTITION.mp3', introEnd: 38, chorusStart: 130, revealDuration: 8 },
  { id: 13, title: 'Neverender', artist: 'Justice (starring Tame Impala)', file: 'audio/NEVERENDER.mp3', introEnd: 30, chorusStart: 80, revealDuration: 8 },
  { id: 14, title: 'Smells Like Teen Spirit', artist: 'Nirvana', file: 'audio/SMELLS_LIKE_TEEN.mp3', introEnd: 25, chorusStart: 140, revealDuration: 8 },
  { id: 15, title: 'Atlantis To Interzone', artist: 'Klaxons', file: 'audio/ATLANTIS.mp3', introEnd: 29, chorusStart: 150, revealDuration: 8 },
  { id: 16, title: 'Hey Little World', artist: 'The Hives', file: 'audio/HEY_LITTLE_WORLD.mp3', introEnd: 24, chorusStart: 48, revealDuration: 8 },
  { id: 17, title: 'Alors On Danse', artist: 'Stromae', file: 'audio/ALORS_ON_DANSE.mp3', introEnd: 15, chorusStart: 47, revealDuration: 8 },
  { id: 18, title: 'Let’s Get It Started', artist: 'The Black Eyed Peas', file: 'audio/LETS_GET_IT_STARTED.mp3', introEnd: 20, chorusStart: 48, revealDuration: 8 },
  { id: 19, title: 'Take Me Out', artist: 'Franz Ferdinand', file: 'audio/TAKE_ME_OUT.mp3', introEnd: 19, chorusStart: 65, revealDuration: 8 },
  { id: 20, title: 'Jocker And The Thief', artist: 'Wolfmother', file: 'audio/JOCKER_AND_THIEF.mp3', introEnd: 40, chorusStart: 88, revealDuration: 8 },
  { id: 21, title: 'Everlong', artist: 'Foo Fighters', file: 'audio/EVERLONG.mp3', introEnd: 28, chorusStart: 50, revealDuration: 8 },
  { id: 22, title: 'New Person, Same Old Mistakes', artist: 'Tame Impala', file: 'audio/NEW_PERSON.mp3', introEnd: 40, chorusStart: 80, revealDuration: 8 },
  { id: 23, title: 'Gangsta’s Paradise', artist: 'Coolio', file: 'audio/GANGSTAS_PARADISE.mp3', introEnd: 10, chorusStart: 48, revealDuration: 8 },
  { id: 24, title: 'Seven Nation Army', artist: 'The Whites Stripes', file: 'audio/SEVEN_NATION_ARMY.mp3', introEnd: 14, chorusStart: 50, revealDuration: 8 },
  { id: 25, title: 'Murder on the Dance Floor', artist: 'Sophie Ellis-Bextor', file: 'audio/MURDER_DANCEFLOOR.mp3', introEnd: 17, chorusStart: 37, revealDuration: 8 },
  { id: 26, title: 'Running Up That Hill', artist: 'Kate Bush', file: 'audio/RUNNING_HILL.mp3', introEnd: 17, chorusStart: 43, revealDuration: 8 },
  { id: 27, title: 'Good Times', artist: 'Chic', file: 'audio/GOOD_TIMES.mp3', introEnd: 16, chorusStart: 18, revealDuration: 8 },
  { id: 28, title: 'Hells Bells', artist: 'AC/DC', file: 'audio/HELLS_BELLS.mp3', introEnd: 100, chorusStart: 170, revealDuration: 8 },
  { id: 29, title: 'Do I Wanna Know ?', artist: 'Arctic Monkeys', file: 'audio/DO_I_WANNA_KNOW.mp3', introEnd: 27, chorusStart: 94, revealDuration: 8 },
  { id: 30, title: 'Down The Road ', artist: 'C2C', file: 'audio/DOWN_THE_ROAD.mp3', introEnd: 30, chorusStart: 50, revealDuration: 8 },
  { id: 31, title: 'Da Funk', artist: 'Daft Punk', file: 'audio/DA_FUNK.mp3', introEnd: 17, chorusStart: 300, revealDuration: 8 },
  { id: 32, title: 'Fallin’', artist: 'Alicia Keys', file: 'audio/FALLIN.mp3', introEnd: 22, chorusStart: 39, revealDuration: 8 },
  { id: 33, title: 'Aventurier', artist: 'Indochine', file: 'audio/AVENTURIER.mp3', introEnd: 23, chorusStart: 140, revealDuration: 8 },
  { id: 34, title: 'Holiday', artist: 'Madonna', file: 'audio/HOLIDAY.mp3', introEnd: 15, chorusStart: 78, revealDuration: 8 },
  { id: 35, title: 'Pump It', artist: 'The Black Eyed Peas', file: 'audio/PUMP_IT.mp3', introEnd: 17, chorusStart: 19, revealDuration: 8 },
  { id: 36, title: 'Enjoy The Silence', artist: 'Depeche Mode', file: 'audio/ENJOY_SILENCE.mp3', introEnd: 25, chorusStart: 43, revealDuration: 8 },
  { id: 37, title: 'Faint', artist: 'Linkin Park', file: 'audio/FAINT.mp3', introEnd: 16, chorusStart: 50, revealDuration: 8 },
  { id: 38, title: 'Ghost', artist: 'Skip The Use', file: 'audio/GHOST.mp3', introEnd: 8, chorusStart: 48, revealDuration: 8 },
  { id: 39, title: 'Boys Don’t Cry', artist: 'The Cure', file: 'audio/BOYS_DONT_CRY.mp3', introEnd: 8, chorusStart: 45, revealDuration: 8 },
  { id: 40, title: 'Lets Get It Done', artist: 'Marvin Gaye', file: 'audio/LETS_GET_IT.mp3', introEnd: 6, chorusStart: 23, revealDuration: 8 },
  { id: 41, title: 'Titre 41 à définir', artist: 'Artiste 41 à définir', file: 'audio/41.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 42, title: 'Titre 42 à définir', artist: 'Artiste 42 à définir', file: 'audio/42.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 43, title: 'Titre 43 à définir', artist: 'Artiste 43 à définir', file: 'audio/43.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 44, title: 'Titre 44 à définir', artist: 'Artiste 44 à définir', file: 'audio/44.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 45, title: 'Titre 45 à définir', artist: 'Artiste 45 à définir', file: 'audio/45.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 46, title: 'Titre 46 à définir', artist: 'Artiste 46 à définir', file: 'audio/46.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 47, title: 'Titre 47 à définir', artist: 'Artiste 47 à définir', file: 'audio/47.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 48, title: 'Titre 48 à définir', artist: 'Artiste 48 à définir', file: 'audio/48.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 49, title: 'Titre 49 à définir', artist: 'Artiste 49 à définir', file: 'audio/49.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 50, title: 'Titre 50 à définir', artist: 'Artiste 50 à définir', file: 'audio/50.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
];