// Liste des 50 chansons du blind test.
// - file          : chemin vers le fichier audio (à placer dans le dossier audio/)
// - introEnd      : durée en secondes de l'intro complète (niveau NOOB)
// - chorusStart   : seconde à laquelle démarre le refrain (lecture auto après la réponse)
// - revealDuration: durée en secondes du refrain joué lors de la révélation
const SONGS = [
  { id: 1, title: 'Bad', artist: 'Michael Jackson', file: 'audio/BAD.mp3', introEnd: 17, chorusStart: 130, revealDuration: 8 }, // exemple repris de ta maquette
  { id: 2, title: 'Banquet', artist: 'Bloc Party', file: 'audio/BANQUET.mp3', introEnd: 18, chorusStart: 58, revealDuration: 8 },
  { id: 3, title: 'Kids', artist: 'MGMT', file: 'audio/KIDS.mp3', introEnd: 50, chorusStart: 148, revealDuration: 8 },
  { id: 4, title: 'Kiss', artist: 'Prince', file: 'audio/KISS.mp3', introEnd: 10, chorusStart: 57, revealDuration: 8 },
  { id: 5, title: 'Song 2', artist: 'Blur', file: 'audio/SONG2.mp3', introEnd: 29, chorusStart: 45, revealDuration: 8 },
  { id: 6, title: 'Bohemian like you', artist: 'The Dandy Warhols', file: 'audio/BOHEMIAN.mp3', introEnd: 37, chorusStart: 125, revealDuration: 8 },
  { id: 7, title: 'Can’t Hold Us', artist: 'Macklemore & Ryan Lewis', file: 'audio/HOLD_US.mp3', introEnd: 18, chorusStart: 151, revealDuration: 8 },
  { id: 8, title: 'Can’t Stop', artist: 'Red Hot Chili Peppers', file: 'audio/CANT_STOP.mp3', introEnd: 32, chorusStart: 114, revealDuration: 8 },
  { id: 9, title: 'I Was Made For Lovin You', artist: 'KISS', file: 'audio/MADE_FOR_LOVIN_YOU.mp3', introEnd: 33, chorusStart: 108, revealDuration: 8 },
  { id: 10, title: 'Thunderstruck', artist: 'AC/DC', file: 'audio/THUNDERSTRUCK.mp3', introEnd: 102, chorusStart: 243, revealDuration: 8 },
  { id: 11, title: 'Feel Good', artist: 'Gorillaz', file: 'audio/FEEL_GOOD.mp3', introEnd: 34, chorusStart: 105, revealDuration: 8 },
  { id: 12, title: 'Titre 12 à définir', artist: 'Artiste 12 à définir', file: 'audio/12.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 13, title: 'Titre 13 à définir', artist: 'Artiste 13 à définir', file: 'audio/13.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 14, title: 'Titre 14 à définir', artist: 'Artiste 14 à définir', file: 'audio/14.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 15, title: 'Titre 15 à définir', artist: 'Artiste 15 à définir', file: 'audio/15.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 16, title: 'Titre 16 à définir', artist: 'Artiste 16 à définir', file: 'audio/16.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 17, title: 'Titre 17 à définir', artist: 'Artiste 17 à définir', file: 'audio/17.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 18, title: 'Titre 18 à définir', artist: 'Artiste 18 à définir', file: 'audio/18.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 19, title: 'Titre 19 à définir', artist: 'Artiste 19 à définir', file: 'audio/19.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 20, title: 'Titre 20 à définir', artist: 'Artiste 20 à définir', file: 'audio/20.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 21, title: 'Titre 21 à définir', artist: 'Artiste 21 à définir', file: 'audio/21.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 22, title: 'Titre 22 à définir', artist: 'Artiste 22 à définir', file: 'audio/22.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 23, title: 'Titre 23 à définir', artist: 'Artiste 23 à définir', file: 'audio/23.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 24, title: 'Titre 24 à définir', artist: 'Artiste 24 à définir', file: 'audio/24.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 25, title: 'Titre 25 à définir', artist: 'Artiste 25 à définir', file: 'audio/25.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 26, title: 'Titre 26 à définir', artist: 'Artiste 26 à définir', file: 'audio/26.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 27, title: 'Titre 27 à définir', artist: 'Artiste 27 à définir', file: 'audio/27.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 28, title: 'Titre 28 à définir', artist: 'Artiste 28 à définir', file: 'audio/28.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 29, title: 'Titre 29 à définir', artist: 'Artiste 29 à définir', file: 'audio/29.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 30, title: 'Titre 30 à définir', artist: 'Artiste 30 à définir', file: 'audio/30.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 31, title: 'Titre 31 à définir', artist: 'Artiste 31 à définir', file: 'audio/31.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 32, title: 'Titre 32 à définir', artist: 'Artiste 32 à définir', file: 'audio/32.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 33, title: 'Titre 33 à définir', artist: 'Artiste 33 à définir', file: 'audio/33.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 34, title: 'Titre 34 à définir', artist: 'Artiste 34 à définir', file: 'audio/34.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 35, title: 'Titre 35 à définir', artist: 'Artiste 35 à définir', file: 'audio/35.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 36, title: 'Titre 36 à définir', artist: 'Artiste 36 à définir', file: 'audio/36.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 37, title: 'Titre 37 à définir', artist: 'Artiste 37 à définir', file: 'audio/37.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 38, title: 'Titre 38 à définir', artist: 'Artiste 38 à définir', file: 'audio/38.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 39, title: 'Titre 39 à définir', artist: 'Artiste 39 à définir', file: 'audio/39.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 40, title: 'Titre 40 à définir', artist: 'Artiste 40 à définir', file: 'audio/40.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 41, title: 'Titre 41 à définir', artist: 'Artiste 41 à définir', file: 'audio/41.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 42, title: 'Titre 42 à définir', artist: 'Artiste 42 à définir', file: 'audio/42.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 43, title: 'Titre 43 à définir', artist: 'Artiste 43 à définir', file: 'audio/43.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 44, title: 'Titre 44 à définir', artist: 'Artiste 44 à définir', file: 'audio/44.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 45, title: 'Titre 45 à définir', artist: 'Artiste 45 à définir', file: 'audio/45.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 46, title: 'Titre 46 à définir', artist: 'Artiste 46 à définir', file: 'audio/46.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 47, title: 'Titre 47 à définir', artist: 'Artiste 47 à définir', file: 'audio/47.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 48, title: 'Titre 48 à définir', artist: 'Artiste 48 à définir', file: 'audio/48.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 49, title: 'Titre 49 à définir', artist: 'Artiste 49 à définir', file: 'audio/49.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
  { id: 50, title: 'Titre 50 à définir', artist: 'Artiste 50 à définir', file: 'audio/50.mp3', introEnd: 8, chorusStart: 30, revealDuration: 8 },
];