// Liste des 50 chansons du blind test.
// - file          : chemin vers le fichier audio (à placer dans le dossier audio/)
// - introEnd      : durée en secondes de l'intro complète (niveau NOOB)
// - chorusStart   : seconde à laquelle démarre le refrain (lecture auto après la réponse)
// - revealDuration: durée en secondes du refrain joué lors de la révélation
// - gain          : multiplicateur de volume appliqué à la lecture pour égaliser le
//                   ressenti sonore entre les 55 chansons (calculé à partir de la loudness
//                   intégrée en LUFS de chaque fichier, cible -16 LUFS avec 1 dB de marge
//                   sous 0 dBFS pour éviter la saturation). 1 = volume d'origine,
//                   < 1 = on baisse, > 1 = on remonte les pistes trop discrètes.
const SONGS = [
  { id: 1, title: 'Bad', artist: 'Michael Jackson', file: 'audio/BAD.mp3', introEnd: 17, chorusStart: 130, revealDuration: 8, gain: 0.445 }, // exemple repris de ta maquette
  { id: 2, title: 'Banquet', artist: 'Bloc Party', file: 'audio/BANQUET.mp3', introEnd: 18, chorusStart: 58, revealDuration: 8, gain: 0.428 },
  { id: 3, title: 'Kids', artist: 'MGMT', file: 'audio/KIDS.mp3', introEnd: 50, chorusStart: 148, revealDuration: 8, gain: 0.498 },
  { id: 4, title: 'Kiss', artist: 'Prince', file: 'audio/KISS.mp3', introEnd: 10, chorusStart: 57, revealDuration: 8, gain: 0.992 },
  { id: 5, title: 'Song 2', artist: 'Blur', file: 'audio/SONG2.mp3', introEnd: 29, chorusStart: 45, revealDuration: 8, gain: 0.432 },
  { id: 6, title: 'Bohemian like you', artist: 'The Dandy Warhols', file: 'audio/BOHEMIAN.mp3', introEnd: 37, chorusStart: 125, revealDuration: 8, gain: 0.502 },
  { id: 7, title: 'Can’t Hold Us', artist: 'Macklemore & Ryan Lewis', file: 'audio/HOLD_US.mp3', introEnd: 18, chorusStart: 151, revealDuration: 8, gain: 0.397 },
  { id: 8, title: 'Can’t Stop', artist: 'Red Hot Chili Peppers', file: 'audio/CANT_STOP.mp3', introEnd: 32, chorusStart: 114, revealDuration: 8, gain: 0.836 },
  { id: 9, title: 'I Was Made For Lovin You', artist: 'KISS', file: 'audio/MADE_FOR_LOVIN_YOU.mp3', introEnd: 33, chorusStart: 108, revealDuration: 8, gain: 0.498 },
  { id: 10, title: 'Thunderstruck', artist: 'AC/DC', file: 'audio/THUNDERSTRUCK.mp3', introEnd: 102, chorusStart: 243, revealDuration: 8, gain: 0.444 },
  { id: 11, title: 'Feel Good', artist: 'Gorillaz', file: 'audio/FEEL_GOOD.mp3', introEnd: 34, chorusStart: 160, revealDuration: 8, gain: 0.553 },
  { id: 12, title: 'Superstition', artist: 'Stevie Wonder', file: 'audio/SUPERSTITION.mp3', introEnd: 38, chorusStart: 130, revealDuration: 8, gain: 0.825 },
  { id: 13, title: 'Neverender', artist: 'Justice (starring Tame Impala)', file: 'audio/NEVERENDER.mp3', introEnd: 30, chorusStart: 80, revealDuration: 8, gain: 0.436 },
  { id: 14, title: 'Smells Like Teen Spirit', artist: 'Nirvana', file: 'audio/SMELLS_LIKE_TEEN.mp3', introEnd: 25, chorusStart: 140, revealDuration: 8, gain: 0.461 },
  { id: 15, title: 'Atlantis To Interzone', artist: 'Klaxons', file: 'audio/ATLANTIS.mp3', introEnd: 29, chorusStart: 150, revealDuration: 8, gain: 0.361 },
  { id: 16, title: 'Hey Little World', artist: 'The Hives', file: 'audio/HEY_LITTLE_WORLD.mp3', introEnd: 24, chorusStart: 48, revealDuration: 8, gain: 0.308 },
  { id: 17, title: 'Alors On Danse', artist: 'Stromae', file: 'audio/ALORS_ON_DANSE.mp3', introEnd: 15, chorusStart: 47, revealDuration: 8, gain: 0.627 },
  { id: 18, title: 'Let’s Get It Started', artist: 'The Black Eyed Peas', file: 'audio/LETS_GET_IT_STARTED.mp3', introEnd: 20, chorusStart: 48, revealDuration: 8, gain: 0.412 },
  { id: 19, title: 'Take Me Out', artist: 'Franz Ferdinand', file: 'audio/TAKE_ME_OUT.mp3', introEnd: 19, chorusStart: 65, revealDuration: 8, gain: 0.656 },
  { id: 20, title: 'Jocker And The Thief', artist: 'Wolfmother', file: 'audio/JOCKER_AND_THIEF.mp3', introEnd: 40, chorusStart: 88, revealDuration: 8, gain: 2.944 },
  { id: 21, title: 'Everlong', artist: 'Foo Fighters', file: 'audio/EVERLONG.mp3', introEnd: 28, chorusStart: 50, revealDuration: 8, gain: 0.439 },
  { id: 22, title: 'New Person, Same Old Mistakes', artist: 'Tame Impala', file: 'audio/NEW_PERSON.mp3', introEnd: 40, chorusStart: 80, revealDuration: 8, gain: 0.44 },
  { id: 23, title: 'Gangsta’s Paradise', artist: 'Coolio', file: 'audio/GANGSTAS_PARADISE.mp3', introEnd: 10, chorusStart: 48, revealDuration: 8, gain: 0.512 },
  { id: 24, title: 'Seven Nation Army', artist: 'The Whites Stripes', file: 'audio/SEVEN_NATION_ARMY.mp3', introEnd: 14, chorusStart: 50, revealDuration: 8, gain: 0.613 },
  { id: 25, title: 'Murder on the Dance Floor', artist: 'Sophie Ellis-Bextor', file: 'audio/MURDER_DANCEFLOOR.mp3', introEnd: 17, chorusStart: 37, revealDuration: 8, gain: 0.499 },
  { id: 26, title: 'Running Up That Hill', artist: 'Kate Bush', file: 'audio/RUNNING_HILL.mp3', introEnd: 17, chorusStart: 43, revealDuration: 8, gain: 0.919 },
  { id: 27, title: 'Good Times', artist: 'Chic', file: 'audio/GOOD_TIMES.mp3', introEnd: 16, chorusStart: 18, revealDuration: 8, gain: 0.862 },
  { id: 28, title: 'Hells Bells', artist: 'AC/DC', file: 'audio/HELLS_BELLS.mp3', introEnd: 100, chorusStart: 170, revealDuration: 8, gain: 0.579 },
  { id: 29, title: 'Do I Wanna Know ?', artist: 'Arctic Monkeys', file: 'audio/DO_I_WANNA_KNOW.mp3', introEnd: 27, chorusStart: 94, revealDuration: 8, gain: 0.613 },
  { id: 30, title: 'Down The Road ', artist: 'C2C', file: 'audio/DOWN_THE_ROAD.mp3', introEnd: 30, chorusStart: 50, revealDuration: 8, gain: 0.495 },
  { id: 31, title: 'Da Funk', artist: 'Daft Punk', file: 'audio/DA_FUNK.mp3', introEnd: 17, chorusStart: 300, revealDuration: 8, gain: 0.573 },
  { id: 32, title: 'Fallin’', artist: 'Alicia Keys', file: 'audio/FALLIN.mp3', introEnd: 22, chorusStart: 39, revealDuration: 8, gain: 0.73 },
  { id: 33, title: 'Aventurier', artist: 'Indochine', file: 'audio/AVENTURIER.mp3', introEnd: 23, chorusStart: 140, revealDuration: 8, gain: 0.665 },
  { id: 34, title: 'Holiday', artist: 'Madonna', file: 'audio/HOLIDAY.mp3', introEnd: 15, chorusStart: 78, revealDuration: 8, gain: 0.725 },
  { id: 35, title: 'Pump It', artist: 'The Black Eyed Peas', file: 'audio/PUMP_IT.mp3', introEnd: 17, chorusStart: 19, revealDuration: 8, gain: 0.401 },
  { id: 36, title: 'Enjoy The Silence', artist: 'Depeche Mode', file: 'audio/ENJOY_SILENCE.mp3', introEnd: 25, chorusStart: 43, revealDuration: 8, gain: 0.533 },
  { id: 37, title: 'Faint', artist: 'Linkin Park', file: 'audio/FAINT.mp3', introEnd: 16, chorusStart: 50, revealDuration: 8, gain: 0.372 },
  { id: 38, title: 'Ghost', artist: 'Skip The Use', file: 'audio/GHOST.mp3', introEnd: 8, chorusStart: 48, revealDuration: 8, gain: 1.334 },
  { id: 39, title: 'Boys Don’t Cry', artist: 'The Cure', file: 'audio/BOYS_DONT_CRY.mp3', introEnd: 8, chorusStart: 45, revealDuration: 8, gain: 1.056 },
  { id: 40, title: 'Lets Get It Done', artist: 'Marvin Gaye', file: 'audio/LETS_GET_IT.mp3', introEnd: 6, chorusStart: 23, revealDuration: 8, gain: 0.901 },
  { id: 41, title: 'Bring Me To Life', artist: 'Evanescence', file: 'audio/BRING_ME_TO_LIFE.mp3', introEnd: 10, chorusStart: 51, revealDuration: 8, gain: 0.376 },
  { id: 42, title: 'Where Is My Mind', artist: 'Pixies', file: 'audio/WHERE_IS_MIND.mp3', introEnd: 16, chorusStart: 35, revealDuration: 8, gain: 0.946 },
  { id: 43, title: 'The Sweet Escape', artist: 'Gwen Stefani', file: 'audio/SWEET_ESCAPE.mp3', introEnd: 30, chorusStart: 47, revealDuration: 8, gain: 0.452 },
  { id: 44, title: 'FunkyTown', artist: 'Lipps Inc.', file: 'audio/FUNKY_TOWN.mp3', introEnd: 11, chorusStart: 69, revealDuration: 8, gain: 0.484 },
  { id: 45, title: 'Still D.R.E', artist: 'Dr. Dre', file: 'audio/STILL_DRE.mp3', introEnd: 20, chorusStart: 45, revealDuration: 8, gain: 0.437 },
  { id: 46, title: 'Smooth Operator', artist: 'Sade', file: 'audio/SMOOTH_OPERATOR.mp3', introEnd: 23, chorusStart: 79, revealDuration: 8, gain: 0.51 },
  { id: 47, title: 'Smoke On The Water', artist: 'Deep Purple', file: 'audio/SMOKE_ON_THE_WATER.mp3', introEnd: 50, chorusStart: 95, revealDuration: 8, gain: 0.61 },
  { id: 48, title: 'Hotel California', artist: 'Eagles', file: 'audio/HOTEL_CALIFORNIA.mp3', introEnd: 50, chorusStart: 118, revealDuration: 8, gain: 0.822 },
  { id: 49, title: 'She Wolf', artist: 'Shakira', file: 'audio/WOLF.mp3', introEnd: 27, chorusStart: 65, revealDuration: 8, gain: 0.757 },
  { id: 50, title: 'Lose Yourself', artist: 'Eminem', file: 'audio/LOSE_YOURSELF.mp3', introEnd: 28, chorusStart: 96, revealDuration: 8, gain: 0.457 },
  { id: 51, title: 'September', artist: 'Earth, Wind and Fire', file: 'audio/SEPTEMBER.mp3', introEnd: 20, chorusStart: 50, revealDuration: 8, gain: 0.762 },
  { id: 52, title: 'Jump To It', artist: 'Aretha Franklin', file: 'audio/JUMP_TO_IT.mp3', introEnd: 10, chorusStart: 120, revealDuration: 8, gain: 0.679 },
  { id: 53, title: 'Toxicity', artist: 'System Of A Down', file: 'audio/TOXICITY.mp3', introEnd: 12, chorusStart: 76, revealDuration: 8, gain: 0.31 },
  { id: 54, title: 'It’s Raining Men', artist: 'The Weather Girls', file: 'audio/RAINING_MEN.mp3', introEnd: 14, chorusStart: 57, revealDuration: 8, gain: 1.053 },
  { id: 55, title: 'Le Graal', artist: 'Kyo', file: 'audio/GRAAL.mp3', introEnd: 15, chorusStart: 47, revealDuration: 8, gain: 0.428 },
];